name: Build and deploy yrkesskade-kodeverk
on:
  push:
    branches:
      - main

env:
  IMAGE: "ghcr.io/${{ github.repository }}:${{ github.sha }}"
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/cache@v2"
        with:
          path: "~/.m2/repository"
          key: "${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}"
          restore-keys: "${{ runner.os }}-maven-"
      - uses: "actions/setup-java@v1"
        with:
          java-version: 11
      - name: Compile and run tests
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_PASSWORD: ${{ secrets.READER_TOKEN }}
        run: "mvn install --settings .m2/maven-settings.xml --file pom.xml"
      - name: Login to Github Docker Registry
        uses: "docker/login-action@v1"
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the Docker image
        run: "docker build --pull --tag ${IMAGE} --tag latest . && docker push ${IMAGE}"

  deploy-to-dev:
    name: Deploy app to dev
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: "actions/checkout@v2"
      - name: Deploy to DEV
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: ./.nais/nais.yaml
          VARS: .nais/dev/vars.yaml
